'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { Score, VB_W } from '@/score/Score';
import { Pneuma, Fermata } from '@/score/marks';
import { COLORS, FONTS } from '@/score/tokens';
import { EXCERPTS } from '@/data/excerpts';
import { useStore } from '@/lib/store';
import { AdmirerLine } from '@/components/AdmirerLine';

const TILE_REVEAL_MS = 1200;
const TILE_FADE_MS = 6000;
const EXCERPT_DURATION_MS = TILE_REVEAL_MS + TILE_FADE_MS + 1200;

const VIS_CX = VB_W / 2;
const VIS_CY = 230;

const SAD = ['melancholic', 'nostalgic', 'tender'];
const INTENSE = ['defiant', 'awed'];
const QUIET = ['peaceful', 'tender', 'nostalgic'];

/** Filename per excerpt index — generated by /api/admin/generate. */
const EXCERPT_AUDIO = ['/audio/gems/sublimity.mp3', '/audio/gems/longing.mp3', '/audio/gems/power.mp3'];

/**
 * Soft Forer probe shown at the third excerpt (memo §1B + §1E). Reads the
 * user's tile pattern across the first two excerpts and picks a flattering
 * specificity that is also a real signal — "I noticed" framing.
 */
function probeFromPriorTiles(prior: string[]): string | null {
  if (prior.length === 0) return null;
  const count = (set: string[]) => prior.filter((t) => set.includes(t)).length;
  const sad = count(SAD);
  const intense = count(INTENSE);
  const quiet = count(QUIET);
  if (sad >= 2 && sad >= intense) {
    return 'You are letting the sad ones land. Most people skip past them.';
  }
  if (intense >= 2 && intense > sad) {
    return 'You are not flinching from the loud ones. That is rarer than it sounds.';
  }
  if (quiet >= 2) {
    return 'You are listening for the quiet places. I will hold you there.';
  }
  return null;
}

export function Gems() {
  const currentExcerpt = useStore((s) => s.currentExcerpt);
  const emotionTiles = useStore((s) => s.emotionTiles);
  const toggleEmotionTile = useStore((s) => s.toggleEmotionTile);
  const nextExcerpt = useStore((s) => s.nextExcerpt);

  const ex = EXCERPTS[currentExcerpt];
  const selected = emotionTiles[currentExcerpt] ?? [];
  const [tilesShown, setTilesShown] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  // Mid-set Forer probe — only at the third excerpt, only if a pattern exists.
  const probeLine = useMemo(() => {
    if (currentExcerpt !== 2) return null;
    const prior = [...(emotionTiles[0] ?? []), ...(emotionTiles[1] ?? [])];
    return probeFromPriorTiles(prior);
  }, [currentExcerpt, emotionTiles]);

  // Auto-play the GEMS excerpt audio. Browsers allow autoplay because the
  // user has already interacted with the page on Phases 0–1.
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;
    audio.currentTime = 0;
    audio.play().catch(() => {
      // Autoplay blocked — silent failure. The visual still progresses.
    });
    return () => {
      audio.pause();
    };
  }, [currentExcerpt]);

  useEffect(() => {
    setTilesShown(false);
    const reveal = window.setTimeout(() => setTilesShown(true), TILE_REVEAL_MS);
    const advance = window.setTimeout(() => nextExcerpt(), EXCERPT_DURATION_MS);
    return () => {
      clearTimeout(reveal);
      clearTimeout(advance);
    };
  }, [currentExcerpt, nextExcerpt]);

  const ROMAN = ['i', 'ii', 'iii', 'iv', 'v', 'vi'][currentExcerpt] ?? '';
  const RING_RADII = [22, 38, 56];

  return (
    <Score
      variant="cream"
      pageTitle="iii. emotion"
      pageNumber={`${currentExcerpt + 1} / ${EXCERPTS.length}`}
      voiceCue={tilesShown ? 'mark anything that lands' : 'listen'}
      footer={`excerpt ${ROMAN} · 15s`}
      overlay={
        <>
          <audio
            ref={audioRef}
            src={EXCERPT_AUDIO[currentExcerpt]}
            preload="auto"
            style={{ display: 'none' }}
          />
          {probeLine && (
            <>
              <div
                style={{
                  position: 'absolute',
                  top: '8%',
                  left: 32,
                  right: 32,
                  textAlign: 'center',
                  fontFamily: FONTS.serif,
                  fontStyle: 'italic',
                  fontSize: 13,
                  lineHeight: 1.45,
                  color: COLORS.scoreAmber,
                  opacity: 0.92,
                  animation: 'sceneFade 1.6s ease-out',
                }}
              >
                {probeLine}
              </div>
              <AdmirerLine text={probeLine} register="elevated" delayMs={500} />
            </>
          )}
          <div
            style={{
              position: 'absolute',
              top: '13%',
              left: 24,
              right: 24,
              textAlign: 'center',
              fontFamily: FONTS.serif,
              fontStyle: 'italic',
              fontSize: 13,
              color: COLORS.inkCreamSecondary,
              letterSpacing: '0.04em',
            }}
          >
            {ex.name.toLowerCase()}
          </div>

          <div
            className="tile-row"
            style={{
              position: 'absolute',
              bottom: '24%',
              left: 24,
              right: 24,
              opacity: tilesShown ? 1 : 0,
              transition: 'opacity 0.6s',
            }}
          >
            {ex.tiles.map((t) => (
              <button
                key={t}
                type="button"
                className={`tile-word${selected.includes(t) ? ' selected' : ''}`}
                onClick={() => toggleEmotionTile(currentExcerpt, t)}
              >
                {t}
              </button>
            ))}
          </div>

          {tilesShown && (
            <div
              style={{
                position: 'absolute',
                bottom: '17%',
                left: 24,
                right: 24,
                height: 1,
                background: COLORS.scoreAmber,
                transformOrigin: 'left center',
                animation: 'countdownBar 6s linear forwards',
              }}
            />
          )}
        </>
      }
    >
      {/* concentric rings of marks pulsing */}
      {RING_RADII.map((r, ringIdx) => {
        const count = 6 + ringIdx * 2;
        return (
          <g key={ringIdx} style={{ transformOrigin: `${VIS_CX}px ${VIS_CY}px` }}>
            {Array.from({ length: count }, (_, i) => {
              const angle = (i / count) * Math.PI * 2 - Math.PI / 2;
              const x = VIS_CX + Math.cos(angle) * r;
              const y = VIS_CY + Math.sin(angle) * r;
              const Mark = ringIdx % 2 === 0 ? Pneuma : Fermata;
              return (
                <g
                  key={i}
                  transform={`translate(${x}, ${y})`}
                  style={{
                    transformOrigin: `${x}px ${y}px`,
                    animation: `markPulse 3.6s ease-in-out infinite`,
                    animationDelay: `${(ringIdx * 0.3 + i * 0.04).toFixed(2)}s`,
                  }}
                >
                  <Mark size={6} color={COLORS.inkCream} opacity={0.4} />
                </g>
              );
            })}
          </g>
        );
      })}
      <circle cx={VIS_CX} cy={VIS_CY} r="3" fill={COLORS.scoreAmber} opacity="0.7" />

      <style>{`
        @keyframes markPulse {
          0%, 100% { opacity: 0.2; transform: scale(0.9); }
          50% { opacity: 0.6; transform: scale(1.1); }
        }
        @keyframes countdownBar {
          from { transform: scaleX(1); }
          to   { transform: scaleX(0); }
        }
      `}</style>
    </Score>
  );
}
